* Fix My Build!

  Oh no! The items changed again! Is my build still good? What should
  I change?

  The objective here is to learn N = # of champions RBMs to predict,
  given a build on the old item set, what one's new build should look
  like.
** Stage 1: Data Collection

   I have a list of match IDs and need to collect match data. If
   possible, I should collect all fields. Ideally later on I can
   predict the most successful builds, but that is another task.

** Problem: Not The Right Data

   I was initially thinking that we could effectively construct a
   mapping Old Build → New Build, but for that we'd need a way to
   identify unique (Old, New) pairs. We don't get any form of user
   IDs. Without a way to divide the data (beyond the per-champion
   level), we get almost nothing because we would have to do what
   amounts to "∀ a in Old, b in New: f(a) ≅ b" (with ≅ read as "could
   equal"). That function "f" is going to be worthless because =a=
   could map to ANY =b=.

   We could potentially rephrase the problem in terms of counters. For
   example: "I am playing A against B. My old build was X. What is my
   new build?"

   I am not convinced that this is going to be a problem we can tackle
   with the data we have.

   The moral of the story is that we need to be concerned with /what
   data we can reliably link/.
